title: Monimen Framework
description: Documentation Governance for AI-Assisted Software Development
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
baseurl: "/monimen"
url: "https://enigmora.github.io"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
